version: "3.0"

services:
  app:
    image: vlakam/socks5-server
#    build:
#      context: .
    environment:
      - SOCKS_USER=user
      - SOCKS_PASS=pass
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
    - 3405:1080